version: "3.0"

expectations:
  population_size: 1000

actions:

  attainment_analysis:
    run: r:v2 analysis/attainment_analysis.R
    outputs:
      moderately_sensitive:
        summary:     output/attainment_summary.csv
        caterpillar: output/school_caterpillar.png
